### ISSUE TITLE
FDS to NES doesn't work

### ISSUE THREAD

**Issue by jadasse** [BleuBleu/FamiStudio#161]
Error: Please contact the developer on GitHub!
Error: Object reference not set to an instance of an object
Error:    at FamiStudio.RomFile.Save(Project originalProject, String filename, Int32[] songIds, String name, String author, Boolean pal) in (path)
Info: Done!

When I tried to convert an FDS extended-project file to an NES rom, I got this error message saying the above. What happened? (and allowing me to copy-paste the log would be nice, too. I had to type it manually, and it cuts off at the path part.)

**Comment by jadasse** [comment]
https://files.catbox.moe/g23o8i.fms

**Comment by BleuBleu** [comment]
It seems to be working here. Just to be sure:
1) I open the file
2) Go to ROM / FDS export 
3) Press export and save

Anything I am missing?

![image](https://user-images.githubusercontent.com/6654334/191449439-2afcabe9-7f98-4f57-99eb-bfd98c8f2872.png)

**Comment by jadasse** [comment]
no. I meant export to nes rom.

**Comment by BleuBleu** [comment]
Oooh, cool! You are right, it DOES crashes if I do that. Thanks, will fix!!

-Mat

**Comment by jadasse** [comment]
Lovely.

**Comment by BleuBleu** [comment]
Fixed 4.0.2.

**Comment by jadasse** [comment]
Wait a minute, you tricked me! The FDS export still doesn't work; it just exports the five 2A03 channels and forgets the FDS channel! WTH?

**Comment by BleuBleu** [comment]
The FDS system uses disk, hence the name "Famicom Disk System". 
That's the only thing it reads, it didn't use cartridges.

-Mat

**Comment by jadasse** [comment]
So, nes export should not be allowed for fds-expanded projects.

**Comment by jadasse** [comment]
As in, it's greyed out or somehing

**Comment by BleuBleu** [comment]
Maybe. I don't really care to be honest. 

Its a very niche feature that almost no one uses. 
I invest the amount of development time proportionally. 
If you want to submit a pull request for it, ill merge it.

-Mat

**Comment by jadasse** [comment]
I would if I knew how to code.
